name: xyz
description: ''
version: 0.0.1
author: harshal@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: xyz
  parentArtefactID: harshalcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2023-11-09 15:40:18'
pipelines:
  pipelines/pipeline-test-3:
    name: pipeline-test-3
    description: ''
    author: harshal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-09 15:40:18'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pipeline-test-3_1:
    name: pipeline-test-3_1
    description: ''
    author: harshal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-09 15:52:08'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pipeline-test-3_2:
    name: pipeline-test-3_2
    description: ''
    author: harshal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-09 15:53:03'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-11-09 15:40:18'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2023-11-09 15:36:00'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-11-09 15:36:00'
pipelineConfigurations: {}
